- id: l1k3
  alias: push HA configuration to GitHub repo
  trigger:
  - at: 00:11:22
    platform: time
  action:
  - data:
      addon: a0d7b954_ssh
      input: /config/scripts/ha_gitpush.sh
    service: hassio.addon_stdin
