- id: l1k3
  alias: push HA configuration to GitHub repo
  trigger:
  - at: 00:11
    platform: time
  action:
  - service: shell_command.github_push
  - service: notify.random_place_on_slack
    data:
      message: Config pushed to GitHub
      title: GitHub
- id: '1640377297758'
  alias: Turn security lights off 14 hours after switch on
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: dc1c082ba6bdf1a02238ac35a23d9ff9
    entity_id: switch.front_lights
    domain: switch
  condition:
  - condition: device
    type: is_on
    device_id: dc1c082ba6bdf1a02238ac35a23d9ff9
    entity_id: switch.front_lights
    domain: switch
  action:
  - delay:
      hours: 14
      minutes: 0
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: dc1c082ba6bdf1a02238ac35a23d9ff9
    entity_id: switch.front_lights
    domain: switch
  mode: single
- id: '1640409763650'
  alias: 'Front Security Lights - ON: Notifcation'
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: dc1c082ba6bdf1a02238ac35a23d9ff9
    entity_id: switch.front_lights
    domain: switch
  condition: []
  action:
  - service: notify.random_place_on_slack
    data:
      message: Front Security Lights switched ON
  mode: single
- id: '1640410380980'
  alias: 'Front Security Lights - OFF: Notifcation'
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: dc1c082ba6bdf1a02238ac35a23d9ff9
    entity_id: switch.front_lights
    domain: switch
  condition: []
  action:
  - service: notify.random_place_on_slack
    data:
      message: Front Security Lights Switched OFF
  mode: single
