homeassistant:
  #  packages: !include_dir_named packages
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_timezone
  name: Home
  external_url: !secret external_url

  allowlist_external_dirs: # changed from whitelist_external_dirs to allowlist_external_dirs in 0.113.0
    - /config/

http:
  server_port: 8123
  #ssl_certificate: /etc/letsencrypt/live/hass.example.com/fullchain.pem
  #ssl_key: /etc/letsencrypt/live/hass.example.com/privkey.pem
  cors_allowed_origins:
    - !secret external_url
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_server
  ip_ban_enabled: false
  login_attempts_threshold: 0

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notify.yaml

shell_command: !include shell_commands.yaml

recorder:
  db_url: !secret homeassistant_mariabd_connecturl
  purge_keep_days: !secret purge_keep_days

discovery:

sensor: !include sensors.yaml
#sensor:
#  - platform: mqtt_room
#    device_id: "study"
#    state_topic: "room-assistant/mqtt-room"

iperf3:
  scan_interval: "01:00"
  monitored_conditions:
    - download
    - upload
  hosts:
    - host: 192.168.0.100
    - host: 192.168.0.101
    - host: 192.168.0.102
