- platform: emoncms
  api_key: !secret emon_api
  url: !secret emon_url

  scan_interval: 5
  id: 1
  unit_of_measurement: "W"
  include_only_feed_id:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11

  sensor_names:
    1: "Feed: Municipal" # Main Switch
    2: "Plugs: Pressure Pump" # Plugs / Pump
    3: "Plugs: Borehole" # Plugs/3
    4: "Plugs: Scullery" # Plugs/4
    5: "Plugs: Kitchen - Microwave+Kettle" # Plugs/5
    6: "Spare 1" # Plugs/6
    7: "Plugs: Main Bed + 2nd" # Plugs/1
    8: "Plugs: 3rd Bed + Study" # Plugs/2
    9: "Plugs: Kitchen - Fridge + Oven" # Plugs/Stove
    10: "Geyser" # Geyser
    11: "Outbuildings" # Outbuildings


- platform: emoncms
  api_key: !secret emon_api
  url: !secret emon_url
  scan_interval: 60
  id: 2
  unit_of_measurement: "kWh"
  include_only_feed_id:
    - 101
    - 102
    - 103
    - 104
    - 105
    - 106
    - 107
    - 108
    - 109
    - 1010
    - 1011

  sensor_names:
    101: "Feed: Municipal"
    102: "Plugs: Pressure Pump"
    103: "Plugs: Borehole"
    104: "Plugs: Scullery"
    105: "Plugs: Kitchen - Microwave+Kettle"
    106: "Spare 1"
    107: "Plugs: Plugs: Main Bed + 2nd"
    108: "Plugs: 3rd Bed + Study"
    109: "Plugs: Kitchen - Fridge + Oven"
    1010: "Geyser"
    1011: "Outbuildings"
