- platform: emoncms
  api_key: !secret emon_api
  url: !secret emon_url
  scan_interval: 5
  id: 1
  unit_of_measurement: "W"
  include_only_feed_id:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11

  sensor_names:
    1: "Feed: Municipal" # Main Switch
    2: "Pressure Pump" # Plugs / Pump
    3: "Borehole" # Plugs/3
    4: "Scullery" # Plugs/4
    5: "Kitchen: Microwave+Kettle" # Plugs/5
    6: "Spare 1" # Plugs/6
    7: "Bedroom Plugs: Main Bed + Spare" # Plugs/1
    8: "Bedroom Plugs: Kids + Study" # Plugs/2
    9: "Kitchen: Fridge + Oven" # Plugs/Stove
    10: "Geyser" # Geyser
    11: "Outbuildings" # Outbuildings

- platform: emoncms
  api_key: !secret emon_api
  url: !secret emon_url
  scan_interval: 60
  id: 2
  unit_of_measurement: "kWh"
  include_only_feed_id:
    - 101
    - 102
    - 103
    - 104
    - 105
    - 106
    - 107
    - 108
    - 109
    - 1010
    - 1011

  sensor_names:
    101: "Feed: Municipal"
    102: "Pressure Pump"
    103: "Borehole"
    104: "Scullery"
    105: "Kitchen: Microwave+Kettle"
    106: "Spare 1"
    107: "Bedroom Plugs: Main Bed + Spare"
    108: "Bedroom Plugs: Kids + Study"
    109: "Kitchen: Fridge + Oven"
    1010: "Feed: Generator"
    1011: "Outbuildings"
